version: '3'
services:
    sqlserver:
        image:   "mcr.microsoft.com/mssql/server:2019-latest"
        hostname: cricketstatssqlserver
        container_name: "cricketstats_graphql"
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Ilchophe4991*!"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        networks:
            - cricket-net
        volumes: 
            - sqlsystem:/var/opt/mssql/
            - sqldata:/var/opt/sqlserver/data
            - sqllog:/var/opt/sqlserver/log
            - sqlbackup:/var/opt/sqlserver/backup

    api:
        image: "cricketstatsgraphqlapi"            
        hostname: "cricketstatsapi"
        container_name: "cricketstatsapi_graphql"
        ports:
            - 8080:80
        networks:
            - cricket-net

networks:
    cricket-net:
        external: true
        name: cricket-net

volumes:
    sqlsystem:
    sqldata:
    sqllog:
    sqlbackup: