version: '3'
services:
    sqlserver:
        image:   "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: "cricketstats_graphql"
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Ilchophe4991*!"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
